// FOLDERS

###
GET http://localhost:3000/api/folders

###
POST http://localhost:3000/api/folders
content-type: application/json

{
    "name": "Training routine",
    "status": "Active"
}

###
PUT http://localhost:3000/api/folders/11
content-type: application/json

{
    "name": "Homework"
}

###
DELETE http://localhost:3000/api/folders/11


// TASKS 

###
GET http://localhost:3000/api/tasks/1

###
POST http://localhost:3000/api/tasks
content-type: application/json

{
    "folder_id": 1,
    "description": "Turn off the light",
    "completed": false
}

###
PUT http://localhost:3000/api/tasks/3
content-type: application/json

{
    "completed": false
}

###
DELETE http://localhost:3000/api/tasks/2